<%@ Page Language="VB" MasterPageFile="~/admin_master.master" AutoEventWireup="false" CodeFile="admin_mag.aspx.vb" Inherits="admin_mag" title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" runat="server" 
    contentplaceholderid="ContentPlaceHolder3">
    <p style="font-family: broadway; font-size: large; font-weight: bolder; font-style: oblique; font-variant: normal; text-transform: inherit">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Magazine Details are given Below:&nbsp;</p>
<p style="font-family: broadway; font-size: large; font-weight: bolder; font-style: oblique; font-variant: normal; text-transform: inherit">
    &nbsp;</p>
<p style="font-family: broadway; font-size: large; font-weight: bolder; font-style: oblique; font-variant: normal; text-transform: inherit">
    <asp:GridView ID="GridView1" runat="server" AllowSorting="True" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        DataSourceID="SqlDataSource1">
        <Columns>
            <asp:CommandField ShowSelectButton="True" />
            <asp:BoundField DataField="c_id" HeaderText="c_id" SortExpression="c_id" />
            <asp:BoundField DataField="magazine_name" HeaderText="magazine_name" 
                SortExpression="magazine_name" />
            <asp:BoundField DataField="dfrom" HeaderText="dfrom" SortExpression="dfrom" />
            <asp:BoundField DataField="dto" HeaderText="dto" SortExpression="dto" />
            <asp:BoundField DataField="ad_page" HeaderText="ad_page" 
                SortExpression="ad_page" />
            <asp:BoundField DataField="ad_size" HeaderText="ad_size" 
                SortExpression="ad_size" />
            <asp:BoundField DataField="issue" HeaderText="issue" SortExpression="issue" />
            <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
            <asp:BoundField DataField="upload_file" HeaderText="upload_file" 
                SortExpression="upload_file" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        SelectCommand="SELECT * FROM [magazine]"></asp:SqlDataSource>
</p>
<p style="font-family: broadway; font-size: large; font-weight: bolder; font-style: oblique; font-variant: normal; text-transform: inherit">
    &nbsp;</p>


</asp:Content>



